version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "pre-build started"
      - pwd
      - ls -lrta
      - echo "Code Scanning..."
     # - mvn clean verify sonar:sonar
      - mvn clean
      - pwd
      - ls -lrt
      - ls -lrta /root/.m2/
      - echo "Code Scanning has been completed!"
  build:
    commands:
      - echo "Build started on $(date)"
      #- mvn clean validate compile test install verify package deploy 
     # - cp -pvr settings.xml /root/.m2
      - ls -lrta
  post_build:
    commands:
      - echo "Build complete on $(date)"
artifacts:
  files:
    - '**/*'
