version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "pre-build started"
      - pwd
      - ls -lrta
  build:
    commands:
      - echo "Build started on $(date)"
      - mvn clean validate compile test install verify package
      - ls -lrta
  post_build:
    commands:
      - echo "Build complete on $(date)"
artifacts:
  files:
    - '**/*'