version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
     #- echo "Fetching secret from Secrets Manager"
     #- export CODEARTIFACT_AUTH_TOKEN=$(aws secretsmanager get-secret-value --secret-id secrete-key --query SecretString --output text)
      - echo "pre-build started"
      - pwd
      - ls -lrta
      - echo "Code Scanning..."
      - mvn clean verify sonar:sonar
      - pwd
      - ls -lrt
      - ls -lrta /root/.m2/
      - cp -pvr settings.xml /root/.m2/
      - ls -lrta /root/.m2/
      - echo "Code Scanning has been completed!"
  build:
    commands:
      - echo "Build started on $(date)"
      - mvn clean validate compile test install verify package deploy
      - ls -lrta
      - apt update -y
      - apt install -y curl
      - curl -u admin:Rajesh@123 -T target/capstone-3.3.6.war "http://54.225.11.152:8080/manager/text/deploy?path=/capstone&update=true"
  post_build:
    commands:
      - echo "Build complete on $(date)"
artifacts:
  files:
    - '**/*'
